In [35]:
import numpy as np

In [36]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [37]:
type(a1)

numpy.ndarray

In [38]:
a2 = np.array(
      [
            [1,2,3],
            [4,5,6]
            ]
               )

a3 = np.array(
      [[[1,2,3],[4,5,6]] , 
               [[1,2,3],[4,5,6]]]
               )

a2
a3



array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [39]:
a1.shape

(3,)

In [40]:

a2.shape

(2, 3)

In [41]:
a3.shape


(2, 2, 3)

In [42]:
a1.ndim , a2.ndim , a3.ndim

(1, 2, 3)

In [43]:
import pandas as pd

df = pd.DataFrame(a2)

In [44]:
random_array = np.random.randint(0,10 , size=(4,3))
random_array

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0]])

In [45]:
random_array.size


12

In [46]:
random_array.shape

(4, 3)

In [47]:
random_array2 = np.random.random((4,2))
random_array2

array([[0.83261985, 0.77815675],
       [0.87001215, 0.97861834],
       [0.79915856, 0.46147936],
       [0.78052918, 0.11827443]])

In [48]:
random_array3 = np.random.rand(4,2)
random_array3

array([[0.63992102, 0.14335329],
       [0.94466892, 0.52184832],
       [0.41466194, 0.26455561],
       [0.77423369, 0.45615033]])

In [49]:
#Her çalıştırıldığında random sayılarn değişmesini önlüyor
np.random.seed(seed=0)
random_array4 = np.random.randint(10 , size=(5,3))
random_array4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [50]:
random_array4.shape

(5, 3)

**Different Viewing arrays and matricies**

In [51]:
a3 = np.array(
      [

       [
        ["a1", "a2", "a3"],
        ["a4", "a5", "a6"],
        ["a7", "a7", "a7"],
        ],


       [
        ["b1", "b2", "b3"],
        ["b4", "b5", "b6"],
        ["b1", "b2", "b3"],
        ],

        [
        ["c1", "c2", "c3"],
        ["c4", "c5", "c6"],
        ["c1", "c2", "c3"],
        ]

        ]
        )

In [52]:
a3[:3 ]


array([[['a1', 'a2', 'a3'],
        ['a4', 'a5', 'a6'],
        ['a7', 'a7', 'a7']],

       [['b1', 'b2', 'b3'],
        ['b4', 'b5', 'b6'],
        ['b1', 'b2', 'b3']],

       [['c1', 'c2', 'c3'],
        ['c4', 'c5', 'c6'],
        ['c1', 'c2', 'c3']]], dtype='<U2')

In [53]:
a3[:3 , :1 ]


array([[['a1', 'a2', 'a3']],

       [['b1', 'b2', 'b3']],

       [['c1', 'c2', 'c3']]], dtype='<U2')

In [54]:
a3[:3 , :1 , :1 ]


array([[['a1']],

       [['b1']],

       [['c1']]], dtype='<U2')

## Arithmatic

In [55]:
a1

array([1, 2, 3])

In [56]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [57]:
a1+ones


array([2., 3., 4.])

In [58]:
a1-ones

array([0., 1., 2.])

In [59]:
a1*ones

array([1., 2., 3.])

In [60]:
a1

array([1, 2, 3])

In [61]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
a1*a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [74]:
a3 = np.array([
      [
       [1,2,3],
       [4,5,6],
       [7,8,9],
      ],
      [
       [11,12,13],
       [14,15,16],
       [17,18,19],

      ],
      [
       [21,22,23],
       [24,25,26],
       [27,28,29],

      ],
])

In [75]:
a1*a3

array([[[ 1,  4,  9],
        [ 4, 10, 18],
        [ 7, 16, 27]],

       [[11, 24, 39],
        [14, 30, 48],
        [17, 36, 57]],

       [[21, 44, 69],
        [24, 50, 78],
        [27, 56, 87]]])

In [76]:
massive_array = np.random.rand(1000)
massive_array[10:]

array([2.35834224e-01, 6.20499900e-01, 6.39622243e-01, 9.48540301e-01,
       7.78276167e-01, 8.48345270e-01, 4.90419908e-01, 1.85348587e-01,
       9.95815293e-01, 1.29355761e-01, 4.71457319e-01, 6.80930992e-02,
       9.43850857e-01, 9.64924941e-01, 7.19389062e-01, 3.49992844e-01,
       2.54382401e-01, 2.65303325e-01, 1.27294025e-01, 5.25808953e-01,
       1.41817276e-01, 3.16730667e-01, 6.26706476e-01, 7.27543610e-01,
       2.42727046e-02, 4.30115984e-01, 6.52124595e-01, 8.53245976e-01,
       4.75324782e-01, 9.69205872e-01, 2.65632548e-01, 1.35087066e-02,
       4.83752865e-01, 2.56113795e-01, 8.23717672e-01, 2.32772672e-01,
       3.10629218e-01, 7.91227431e-01, 7.15143252e-01, 5.58051237e-01,
       7.04948062e-01, 4.18636864e-01, 5.31004761e-03, 1.13551285e-02,
       5.11221788e-01, 8.32909797e-02, 5.10754802e-02, 9.65516639e-01,
       8.59002640e-01, 1.52027227e-01, 6.64218590e-04, 9.41667795e-01,
       2.78325298e-01, 1.85897603e-01, 6.91508108e-01, 1.08903739e-01,
      

In [77]:
# %timeit sum(massive_array)
# %timeit np.sum(massive_array)

In [81]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
a2.shape


(2, 3)

In [84]:
a2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [85]:
a2.T.shape

(3, 2)

## Dot Product

In [87]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))

In [88]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [89]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [94]:
mat2.T

array([[6, 8, 9, 4, 3],
       [7, 1, 8, 3, 5],
       [7, 5, 9, 0, 0]])

In [96]:
## Matriks dot product işlemi yapıyor (Matriks çarpımı)

np.dot(mat1 , mat2.T)

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])